import { bootstrapApplication } from '@angular/platform-browser';
import { RouteReuseStrategy, provideRouter, withPreloading, PreloadAllModules } from '@angular/router';
import { IonicRouteStrategy, provideIonicAngular } from '@ionic/angular/standalone';
import { provideHttpClient, withInterceptors } from '@angular/common/http';

import { routes } from './app/app.routes';
import { AppComponent } from './app/app.component';
import { intercettoreAutenticazione } from './app/core/interceptors/auth-interceptor';
import { addIcons } from 'ionicons';

import {
  addOutline,
  alertCircleOutline,
  arrowBackOutline,
  arrowForwardOutline,
  attachOutline,
  bookOutline,
  businessOutline,
  calendarClearOutline,
  calendarNumberOutline,
  calendarOutline,
  checkmarkCircle,
  checkmarkCircleOutline,
  checkmarkOutline,
  chevronBackOutline,
  chevronForwardOutline,
  closeCircle,
  closeOutline,
  createOutline,
  documentTextOutline,
  eyeOffOutline,
  eyeOutline,
  filterOutline,
  folderOutline,
  helpCircleOutline,
  homeOutline,
  hourglass,
  hourglassOutline,
  informationCircleOutline,
  locationOutline,
  lockClosedOutline,
  logInOutline,
  logoGithub,
  logoLinkedin,
  logOutOutline,
  mailOutline,
  mapOutline,
  notificationsOutline,
  paperPlaneOutline,
  peopleOutline,
  personAddOutline,
  personCircleOutline,
  personOutline,
  schoolOutline,
  searchOutline,
  settingsOutline,
  shieldCheckmarkOutline,
  statsChartOutline,
  timeOutline,
  trashBinOutline,
  trashOutline
} from 'ionicons/icons';

addIcons({
  addOutline,
  alertCircleOutline,
  arrowBackOutline,
  arrowForwardOutline,
  attachOutline,
  bookOutline,
  businessOutline,
  calendarClearOutline,
  calendarNumberOutline,
  calendarOutline,
  checkmarkCircle,
  checkmarkCircleOutline,
  checkmarkOutline,
  chevronBackOutline,
  chevronForwardOutline,
  closeCircle,
  closeOutline,
  createOutline,
  documentTextOutline,
  eyeOffOutline,
  eyeOutline,
  filterOutline,
  folderOutline,
  helpCircleOutline,
  homeOutline,
  hourglass,
  hourglassOutline,
  informationCircleOutline,
  locationOutline,
  lockClosedOutline,
  logInOutline,
  logoGithub,
  logoLinkedin,
  logOutOutline,
  mailOutline,
  mapOutline,
  notificationsOutline,
  paperPlaneOutline,
  peopleOutline,
  personAddOutline,
  personCircleOutline,
  personOutline,
  schoolOutline,
  searchOutline,
  settingsOutline,
  shieldCheckmarkOutline,
  statsChartOutline,
  timeOutline,
  trashBinOutline,
  trashOutline
});

bootstrapApplication(AppComponent, {
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    provideIonicAngular(),
    provideRouter(routes, withPreloading(PreloadAllModules)), 
    provideHttpClient(withInterceptors([intercettoreAutenticazione])),
  ],
});
